# Pulled from http://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Meteor-Apps
# To track tests, visit https://travis-ci.org/

language: node_js
node_js:
  - "0.12"
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh | /bin/sh"
services:
  - mongodb
env:
  - LAIKA_OPTIONS="-t 5000"